### ISSUE TITLE
Ensure tests run offline

### ISSUE THREAD

**Issue by rarkins** [renovateapp/renovate#1538]
I think there are a few cases where our tests are "hitting" servers like npmjs or github. All tests should be mocked/nocked so that they can run offline.

**Comment by rarkins** [comment]
```
FAIL test/workers/pr/changelog.spec.js (5.811s)
  ● workers/pr/changelog › getChangeLogJSON › filters unnecessary warns
    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.
      
      at node_modules/jest-jasmine2/build/queue_runner.js:72:21
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:592:19)
```
