### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: issueList is not iterable

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovateapp/renovate#1775]
#### This is a:

* [x] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [ ] The Renovate GitHub App
* [x] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

I upgraded from `11.37.19` to `11.47.0`, for an on-premise deployment and I began receiving the following error:

```
 INFO: Could not find allowed merge methods for repo (repository=org/repo)
(node:160) UnhandledPromiseRejectionWarning: TypeError: issueList is not iterable
    at Object.ensureIssueClosing (/app/node_modules/renovate/lib/platform/github/index.js:620:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by
```

The `org/repo` project has issues enabled.

**Comment by rarkins** [comment]
1. Do you always get the "Could not find allowed merge methods for repo" message? That means GHE is not allowing us to read "admin" data from the repo, which I don't get on github.com. Can you check if read access to admin data is enabled for your app?

2. Are you able to capture a DEBUG log?

**Comment by rarkins** [comment]
Your previous release is 13 days old.

The `getIssueList()` function hadn't changed in 2 months:
![image](https://user-images.githubusercontent.com/6311784/38205484-143fe6da-36a7-11e8-90f1-147ee19026a4.png)

However 11 days ago I moved where we *call* `ensureIssueClosing()` from in https://github.com/renovateapp/renovate/commit/f0cd0cb8b8d48c4a627c7e504a182e9f6bc7d41d

I have added an `await` to that function call just now and released in v11.47.1, although I hadn't thought it should be needed (my goal was to execute it asynchronously and not actually wait on it)

**Comment by destroyerofbuilds** [comment]
It turns out that I have been receiving the `UnhandledPromiseRejectionWarning: TypeError: issueList is not iterable` error for at least a month (I hadn't noticed it in my logs previously, but looking back, it seems I've been receiving it for a while).

99% of the time it happens right after `INFO: Renovating repository`. Only one case, the case I reported here, do I see `INFO: Could not find allowed merge methods for repo` right before the event.

There are lots of other messages for `INFO: Could not find allowed merge methods for repo` in my logs that aren't followed by a `UnhandledPromiseRejectionWarning` event.

**Comment by destroyerofbuilds** [comment]
> There are lots of other messages for INFO: Could not find allowed merge methods for repo in my logs that aren't followed by a UnhandledPromiseRejectionWarning event.

Actually, `INFO: Could not find allowed merge methods for repo` always appears right after the `UnhandledPromiseRejectionWarning` event.

**Comment by destroyerofbuilds** [comment]
>Are you able to capture a DEBUG log

We don't capture `DEBUG` logs by default (too many messages for our log consumer).

I'll run `DEBUG` locally on just the repository causing this issue to see what I get.

**Comment by rarkins** [comment]
The `UnhandledPromiseRejectionWarning` should hopefully be gone now, as it's called using `await`. The `INFO: Could not find allowed merge methods for repo` message might be a separate GHE app problem.

**Comment by destroyerofbuilds** [comment]
I can't seem to reproduce the error locally (scoping the github app to only process the effected repository).

> The UnhandledPromiseRejectionWarning should hopefully be gone now

I'll deploy the latest version and I'll let you know if `UnhandledPromiseRejectionWarning` shows up again.

**Comment by destroyerofbuilds** [comment]
I deployed `11.47.1`, and I no longer see `UnhandledPromiseRejectionWarning `.
