### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection

### ISSUE THREAD

**Issue by destroyerofbuilds** [renovateapp/renovate#1816]
#### This is a:

* [x] Bug report (non-security related)
* [ ] Feature request
* [ ] I'm not sure which of those it is

#### I'm using:

* [ ] The Renovate GitHub App
* [x] Self-hosted GitHub
* [ ] Self-hosted GitLab
* [ ] Self-hosted VSTS

#### Please describe the issue:

For an on-premise deployment ([11.49.5](https://github.com/renovateapp/renovate/releases/tag/11.49.5)) I've started to receive the following error:

```bash
UnhandledPromiseRejectionWarning: Error: config-validation
     at resolveConfigPresets (/app/node_modules/renovate/lib/config/presets.js:31:25)
     at <anonymous>
     at process._tickCallback (internal/process/next_tick.js:182:7)
UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) 
```

**Comment by rarkins** [comment]
Which version were you using prior to 11.49.5?

**Comment by destroyerofbuilds** [comment]
Version `11.47.6` (Specifically this commit was the commit we used before encountering the errors - https://github.com/renovateapp/github-app-cli/commit/bb5cd58112fd609bc44db7a47830f29b9a367196)

**Comment by rarkins** [comment]
OK I'm looking at https://github.com/renovateapp/renovate/compare/11.47.6...11.49.5 then, thanks
